### ISSUE TITLE
Several Trials: Dead End: no such file or directory, open '/opt/app/package.json'

### ISSUE THREAD

**Issue by brianmugweru** [Osedea/nodock#106]
Been trying to run nodejs in nginx nodock container but I'm missing something and I have no Idea what it is. I'm connecting nginx to nginx-proxy which works properly though I'm hitting error 502 from the browser.
Dead End
npm WARN using --force I sure hope you know what you are doing.
npm WARN saveError ENOENT: no such file or directory, open '/opt/app/package.json'
node_1        | npm WARN saveError EACCES: permission denied, open '/opt/app/package-lock.json.4185245799'
node_1        | npm WARN enoent ENOENT: no such file or directory, open '/opt/app/package.json'
node_1        | npm WARN app No description
node_1        | npm WARN app No repository field.
node_1        | npm WARN app No README data
node_1        | npm WARN app No license field.
and
found 0 vulnerabilities
node_1        | 
node_1        | internal/modules/cjs/loader.js:583
node_1        |     throw err;
node_1        |     ^
node_1        | 
node_1        | Error: Cannot find module '/opt/app/bin/www'
node_1        |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
node_1        |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
node_1        |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
node_1        |     at startup (internal/bootstrap/node.js:266:19)
node_1        |     at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

Using express-generator to run nodejs so entry point is 'node bin/www';
My application has files arranged in the following format
data - folder - contains docker data-nginx
app - folder - contains nodejs
nodock - folder - contains docker folder, files and dockercompose.yml

dockercompose.yml file
version: '3.3'

services:
    node:
        build:
            context: ./node
            args:
                - NODE_VERSION=latest
                - PROJECT_PATH=../app
                - NODE_ENV=development
                - YARN=false
        volumes:
            - ../:/opt/app
        entrypoint: run-nodock "node bin/www"
        tty: true
        networks:
          - frontend
          - backend

    nginx:
        build:
            context: ./nginx
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes:
            - ../data/logs/nginx/:/var/log/nginx
            - ../data/nginx/sites/:/etc/nginx/sites-available
            - ./certbot/certs/:/var/certs
        ports:
            - 80
            - 443
        environment:
            VIRTUAL_HOST: 'domain.test'
        tty: true
        networks:
            - frontend
            - backend

### Networks Setup ############################################
networks:
  frontend:
    external:
       name: nginxproxy_default
  backend:
    driver: "bridge"

Docker version 18.06.0-ce, build 0ffa825
docker-compose version 1.18.0, build 8dd22a9
Ubuntu 16.04 lts
I appreciate any help that comes along

**Comment by brianmugweru** [comment]
I found the solution for it incase anyone ever gets stuck at this point
So The documentation reads change project path to the path you would like for your project [node project path](https://github.com/Osedea/nodock#Node-Project-Path)  which i thought would direct nodock to my project folder directory containing the server but was not the case instead led to several package.json 404s. If hit by directory project paths, leave the project path as is and change the following line [volumes:](https://github.com/Osedea/nodock/blob/f851f5e9080f1419909e3874a9e3b2041751e061/docker-compose.yml#L14) to direct it to your project path in my case it will be ../app:/opt/app, which in the examples case happens to be ../:/opt/app. Happy coding with docker

**Comment by philtrep** [comment]
@brianmugweru I'm a little late to reply, I'll update the documentation to properly indicate the fix. Thanks!
